import 'dart:async';
import 'package:objectbox/objectbox.dart';
import '../models/memory_unit.dart';
import '../../../core/ai/managed_runtime.dart';

class MemoryDaemon {
  final Box<MemoryUnit> _box;
  final ManagedRuntime _runtime;

  MemoryDaemon(this._box, this._runtime);

  void start() {
    // Run consolidation every 24 hours or during device inactivity
    Timer.periodic(const Duration(hours: 24), (timer) {
      consolidate();
    });
  }

  Future<void> consolidate() async {
    // 1. Fetch raw chat logs older than 7 days
    final sevenDaysAgo = DateTime.now().subtract(const Duration(days: 7));
    final query = _box.query(MemoryUnit_.timestamp.lessThan(sevenDaysAgo.millisecondsSinceEpoch)
                .and(MemoryUnit_.isNote.equals(false))).build();
    
    final oldLogs = query.find();
    if (oldLogs.isEmpty) return;

    final sprawlingText = oldLogs.map((e) => e.text).join("\n");
    
    // 2. Use LLM to generate a dense summary
    final prompt = "Summarize the following conversation into concise factual statements for long-term memory:\n$sprawlingText";
    
    String summary = "";
    final completer = Completer<String>();
    
    final subscription = _runtime.tokenStream.listen((token) {
      summary += token;
    }, onDone: () => completer.complete(summary));

    _runtime.generate(prompt);
    final consolidatedText = await completer.future;
    subscription.cancel();

    // 3. Save summary as a new persistent MemoryUnit
    final summaryUnit = MemoryUnit(
      text: consolidatedText,
      timestamp: DateTime.now(),
      isNote: false,
      mood: "neutral",
      // vector will be generated by MemoryService
    );
    _box.put(summaryUnit);

    // 4. Forcefully clear the raw logs to preserve storage
    _box.removeMany(oldLogs.map((e) => e.id).toList());
  }
}
