# flutter_gemma / MediaPipe keep rules
# These prevent R8 from stripping classes needed at runtime by MediaPipe and Protocol Buffers.

# MediaPipe framework
-keep class com.google.mediapipe.** { *; }
-dontwarn com.google.mediapipe.**

# Protocol Buffers (used internally by MediaPipe)
-keep class com.google.protobuf.** { *; }
-dontwarn com.google.protobuf.**

# RAG / Local Agents (flutter_gemma optional feature)
-keep class com.google.ai.edge.localagents.** { *; }
-dontwarn com.google.ai.edge.localagents.**

# Auto-generated by R8 — specific missing proto classes
-dontwarn com.google.mediapipe.proto.CalculatorProfileProto$CalculatorProfile
-dontwarn com.google.mediapipe.proto.GraphTemplateProto$CalculatorGraphTemplate
